"use client"

import { useState } from "react"
import { Activity, BarChart3, Bell, BookOpen, ChevronDown, ClipboardList, GraduationCap, LayoutDashboard, Menu, Search, Settings, ShieldCheck, Users, X } from "lucide-react"

const nav = [
  { label: "Overview", icon: LayoutDashboard },
  { label: "Students", icon: Users, count: "1,248" },
  { label: "Teachers", icon: GraduationCap, count: "86" },
  { label: "Courses", icon: BookOpen },
  { label: "Exams & grading", icon: ClipboardList },
  { label: "Analytics", icon: BarChart3 },
]

const students = [
  ["Emma Andersson", "SA22B", "Active", "92%", "Today"],
  ["Lucas Berg", "TE23A", "Active", "87%", "Yesterday"],
  ["Nora Lindqvist", "NA22C", "At risk", "61%", "2 days ago"],
  ["Oskar Nilsson", "EK23B", "Active", "95%", "3 days ago"],
  ["Alva Karlsson", "SA23A", "Inactive", "44%", "1 week ago"],
]

export function AdminShell() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [active, setActive] = useState("Overview")
  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-border bg-[#0e1720] transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-20 items-center justify-between border-b border-border px-6"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Activity /></div><div><p className="font-semibold tracking-tight">mindful</p><p className="font-mono text-[10px] uppercase tracking-[0.24em] text-muted-foreground">admin console</p></div></div><button className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X /></button></div>
      <nav className="flex flex-1 flex-col gap-1 p-4">{nav.map(({ label, icon: Icon, count }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${active === label ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-4" /> <span className="flex-1">{label}</span>{count && <span className="font-mono text-xs opacity-60">{count}</span>}</button>)}</nav>
      <div className="border-t border-border p-4"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><Settings className="size-4" /> Settings</button><div className="mt-4 flex items-center gap-3 rounded-lg bg-muted/60 p-3"><div className="grid size-8 place-items-center rounded-full bg-accent/20 text-sm font-semibold text-accent">AM</div><div className="min-w-0 flex-1"><p className="truncate text-sm">Anna Magnusson</p><p className="text-xs text-muted-foreground">Administrator</p></div><ChevronDown className="size-4 text-muted-foreground" /></div></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-10 bg-black/50 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}
    <main className="lg:pl-64"><header className="sticky top-0 z-10 flex h-20 items-center gap-4 border-b border-border bg-background/90 px-4 backdrop-blur md:px-8"><button className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu /></button><div className="flex-1"><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Workspace / {active}</p><h1 className="mt-1 text-xl font-semibold tracking-tight">Good morning, Anna</h1></div><button className="hidden items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm text-muted-foreground md:flex"><Search className="size-4" /> Search <kbd className="rounded bg-muted px-1.5 py-0.5 font-mono text-[10px]">⌘K</kbd></button><button className="relative rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Notifications"><Bell className="size-5" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-accent" /></button></header>
      <section className="mx-auto max-w-[1440px] p-4 md:p-8"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm text-primary">Thursday, 28 August 2026</p><h2 className="text-3xl font-semibold tracking-tight">Overview</h2><p className="mt-2 text-muted-foreground">A clear view of what is happening across your school.</p></div><button className="flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90"><ShieldCheck className="size-4" /> Generate report</button></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total students","1,248","+6.4%","from last month"],["Active courses","42","+3","this semester"],["Completion rate","84.7%","+2.1%","from last month"],["Open interventions","18","-12.5%","from last month"]].map(([label,value,change,note],i) => <div key={label} className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between"><p className="text-sm text-muted-foreground">{label}</p><span className={`rounded-full px-2 py-1 font-mono text-[10px] ${i === 3 ? "bg-primary/10 text-primary" : "bg-accent/10 text-accent"}`}>{change}</span></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Learning activity</h3><p className="mt-1 text-sm text-muted-foreground">Student engagement over the last 30 days</p></div><select className="rounded-lg border border-border bg-muted px-3 py-2 text-xs text-foreground"><option>Last 30 days</option><option>Last 90 days</option></select></div><div className="mt-8 flex h-48 items-end gap-2">{[35,48,42,63,54,70,62,81,66,74,88,78,92,76,84,68,79,90,83,96,72,86,91,77,89,94,80,87,98,90].map((height,i) => <div key={i} className="group flex-1"><div style={{ height: `${height}%` }} className="rounded-t-sm bg-primary/60 transition group-hover:bg-primary" /></div>)}</div><div className="mt-4 flex justify-between font-mono text-[10px] text-muted-foreground"><span>01 AUG</span><span>15 AUG</span><span>28 AUG</span></div></div>
      <div className="rounded-xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Needs attention</h3><p className="mt-1 text-sm text-muted-foreground">Students flagged by your team</p></div><button className="text-xs text-primary hover:underline">View all</button></div><div className="mt-5 flex flex-col gap-4">{[["NL","Nora Lindqvist","Attendance below 70%","danger"],["JK","Johan Karlsson","Missing 3 assignments","warn"],["ES","Ella Sjöberg","No activity in 7 days","warn"]].map(([initials,name,reason,type]) => <div key={name} className="flex items-center gap-3"><div className={`grid size-9 place-items-center rounded-full text-xs font-semibold ${type === "danger" ? "bg-danger/15 text-danger" : "bg-accent/15 text-accent"}`}>{initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{name}</p><p className="truncate text-xs text-muted-foreground">{reason}</p></div><span className="size-2 rounded-full bg-danger" /></div>)}</div></div></div>
      <div className="mt-6 rounded-xl border border-border bg-card"><div className="flex flex-col gap-4 border-b border-border p-6 md:flex-row md:items-center md:justify-between"><div><h3 className="font-semibold">Recent students</h3><p className="mt-1 text-sm text-muted-foreground">Latest activity across your student body</p></div><div className="flex gap-2"><button className="rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-muted">Filter</button><button className="rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-muted">Export CSV</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-muted/40 text-xs uppercase tracking-wider text-muted-foreground"><tr>{["Student","Class","Status","Progress","Last active"].map(h => <th key={h} className="px-6 py-3 font-mono font-normal">{h}</th>)}</tr></thead><tbody>{students.map(([name,klass,status,progress,last]) => <tr key={name} className="border-t border-border hover:bg-muted/30"><td className="px-6 py-4 font-medium">{name}</td><td className="px-6 py-4 font-mono text-xs text-muted-foreground">{klass}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs ${status === "Active" ? "bg-primary/10 text-primary" : status === "At risk" ? "bg-accent/10 text-accent" : "bg-muted text-muted-foreground"}`}>{status}</span></td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-20 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: progress }} /></div><span className="font-mono text-xs text-muted-foreground">{progress}</span></div></td><td className="px-6 py-4 text-muted-foreground">{last}</td></tr>)}</tbody></table></div></div></section></main>
  </div>
}
