import { Router } from "express";
import logger from "../utils/logger.js";
import taskRoutes from "./taskRoutes.js";
import authRoutes from "./authRoutes.js";
import studentRoutes from "./studentRoutes.js";
import userRoutes from "./userRoutes.js";
import teacherRoutes from "./teacherRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import programRoutes from "./programRoutes.js";
import gradeRoutes from "./gradeRoutes.js";
import courseRoutes from "./courseRoutes.js";
import coursePackageRoutes from "./coursePackageRoutes.js";
import searchRoutes from "./searchRoutes.js";
import examRoutes from "./examRoutes.js";
import meetingroutes from "./meetingroutes.js";
import notificationRoutes from "./notificationRoutes.js";
import documentRoutes from "./documentRoutes.js";
import statsRoutes from "./statsRoutes.js";
import actionPlanRoutes from "./actionPlanRoutes.js";
import courseMatchingRoutes from "./courseMatchingRoutes.js";
import courseTemplateRoutes from "./courseTemplateRoutes.js";
import teacherScheduleParameterRoutes from "./teacherScheduleParameterRoutes.js";
import studentDetailsRoutes from "./studentDetailsRoutes.js";
import gradeReportRoutes from "./gradeReportRoutes.js";
import gradeCatalogRoutes from "./gradeCatalogRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import inactivityRoutes from "./inactivityRoutes.js";
import messagingRoutes from "./messagingRoutes.js";
import learningRoutes from "./learningRoutes.js";
import chatbotRoutes from "./chatbotRoutes.js";
import faqRoutes from "./faqRoutes.js";
import studyCertificateRoutes from "./studyCertificateRoutes.js";
import auditRoutes from "./auditRoutes.js";
import placementRoutes from "./placementRoutes.js";
import aplRoutes from "./aplRoutes.js";
import courseBankRoutes from "./courseBankRoutes.js";
import questionBankRoutes from "./questionBankRoutes.js";
import certificateRoutes from "./certificateRoutes.js";
import certificateRecordRoutes from "./certificateRecordRoutes.js";

const router = Router();

logger.info("Registering API routes...");

//  Log before mounting each route
router.use("/api", examRoutes);
router.use("/api", taskRoutes);
router.use("/api", authRoutes);
router.use("/api", studentRoutes);
router.use("/api", userRoutes);
router.use("/api", teacherRoutes);
router.use("/api/uploads", uploadRoutes);
router.use("/api", programRoutes);
router.use("/api", gradeRoutes);
router.use("/api", courseRoutes);
router.use("/api", coursePackageRoutes);
router.use("/api", searchRoutes);
router.use("/api", meetingroutes);
router.use("/api", notificationRoutes);
router.use("/api", documentRoutes);
router.use("/api/stats", statsRoutes);
router.use("/api", actionPlanRoutes);
router.use("/api", courseMatchingRoutes);
router.use("/api", courseTemplateRoutes);
router.use("/api", teacherScheduleParameterRoutes);
router.use("/api", studentDetailsRoutes);
router.use("/api", gradeReportRoutes);
router.use("/api", gradeCatalogRoutes);
router.use("/api/analytics", analyticsRoutes);
router.use("/api/inactivity", inactivityRoutes);
router.use("/api", messagingRoutes);
router.use("/api", learningRoutes);
router.use("/api/chatbot", chatbotRoutes);
router.use("/api", faqRoutes);
router.use("/api/course-bank", courseBankRoutes);
router.use("/api/question-bank", questionBankRoutes);
 router.use("/api", studyCertificateRoutes);
 router.use("/api", certificateRoutes);
 router.use("/api", certificateRecordRoutes);
router.use("/api/auditlogs", auditRoutes);
router.use("/api", placementRoutes);
router.use("/api", aplRoutes);

export default router;
